[project]
name = "postlinkedin"
version = "0.1.0"
description = "PostLinkedin using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[litellm,tools]==1.14.2",
    "langchain-groq>=1.1.2",
]

[project.scripts]
kickoff = "postlinkedin.main:kickoff"
run_crew = "postlinkedin.main:kickoff"
plot = "postlinkedin.main:plot"
run_with_trigger = "postlinkedin.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
